spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL_FROM}
  password: ${PASSWORD_APPLICATION_GOOGLE}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true